In [1]:
import numpy as np

In [3]:
x_test=np.loadtxt('test_diabetes_test.csv',delimiter=',')

In [4]:
x_test

array([[ 0.02354575,  0.05068012, -0.0374625 , ..., -0.03949338,
        -0.03075121, -0.01350402],
       [-0.07816532, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.01811827, -0.08391984],
       [-0.03094232,  0.05068012,  0.00133873, ...,  0.1081111 ,
         0.08379677,  0.00306441],
       ...,
       [ 0.0090156 , -0.04464164, -0.01267283, ...,  0.03430886,
         0.02337484, -0.0052198 ],
       [ 0.01991321, -0.04464164, -0.03422907, ...,  0.03283281,
         0.02472532,  0.06933812],
       [ 0.01628068,  0.05068012,  0.00996123, ..., -0.03949338,
         0.01703713,  0.00720652]])

In [5]:
data=np.loadtxt('training_diabetes_train.csv',delimiter=',')

In [8]:
x=data[:,0:10]

In [9]:
x

array([[-0.04910502, -0.04464164,  0.16085492, ...,  0.03430886,
         0.02801651,  0.01134862],
       [-0.07090025,  0.05068012, -0.08919748, ..., -0.00259226,
        -0.01290794, -0.05492509],
       [ 0.00175052, -0.04464164, -0.07087468, ..., -0.03949338,
        -0.02251217,  0.00720652],
       ...,
       [ 0.02354575, -0.04464164,  0.0703187 , ..., -0.00259226,
        -0.01919705, -0.00936191],
       [ 0.01628068,  0.05068012,  0.07247433, ..., -0.00259226,
        -0.02364456,  0.06105391],
       [-0.00914709,  0.05068012, -0.03099563, ..., -0.00259226,
         0.00620932,  0.02791705]])

In [10]:
y=data[:,10]

In [11]:
y

array([346., 104.,  49., 180., 110.,  72.,  68., 216.,  47., 296.,  65.,
        96.,  67.,  52., 100., 202., 128.,  63., 281., 152., 124., 245.,
       101., 113.,  48., 197., 186., 132., 245.,  91.,  43., 101., 111.,
       199., 220., 281., 217.,  93., 174., 150., 206.,  61.,  55., 118.,
        53., 275., 215., 142.,  90.,  65., 200.,  96., 249., 200., 155.,
       170., 141., 179., 225.,  61., 103., 131., 158., 275., 246.,  97.,
       302.,  91., 178.,  51., 170., 104., 168., 257., 182.,  71., 220.,
       241., 192., 220., 220., 141.,  89., 144., 150., 135., 200.,  39.,
        25., 185.,  52.,  92.,  63., 152.,  69.,  68., 274., 279., 236.,
       168., 143., 135., 123., 277.,  60.,  72.,  72., 109.,  86.,  92.,
        99.,  48., 170., 283., 129.,  75., 270., 272.,  31., 262., 232.,
       191., 140., 233., 196., 263.,  88.,  84., 137., 128.,  78., 140.,
       252.,  55., 104., 235.,  37., 122.,  72., 144., 138., 253.,  90.,
        53., 198., 145.,  73., 252.,  77., 295., 24

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg1=LinearRegression()

In [14]:
reg1.fit(x,y)

LinearRegression()

In [15]:
reg1.coef_

array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
       -833.11088526,  525.74313633,  136.07129167,  140.89458927,
        731.44498492,   53.32119133])

In [16]:
reg1.intercept_

150.702574894566

In [17]:
y_predict_data=reg1.predict(x_test)

In [18]:
y_predict_data

array([105.52974799, 105.8039198 , 178.60857225,  79.3828781 ,
        52.95868706,  98.87263854, 150.71755448,  34.86515216,
       113.13535727, 161.50184038, 135.8615611 ,  94.71592222,
       138.48094422, 141.37441723, 158.76862662, 171.65288616,
       106.44835654, 103.92659639,  95.38693889, 167.40118092,
       166.53426278, 101.53464712, 252.45035972, 147.02258547,
       214.78906632, 161.27557106, 210.61315228,  71.78091585,
       189.65032431, 206.6134259 , 219.98643455, 168.80192534,
       116.84846127, 178.74399639,  77.03247418,  59.54633214,
       111.5673781 , 156.95186739, 154.59591259, 198.94457493,
       115.53884017, 153.46699024,  84.96179518, 113.70337192,
       142.14155617, 147.31040378,  82.78072358,  77.89237327,
       128.99006192, 261.58712282, 213.31187775, 243.98791257,
       167.68132094, 183.69712124, 166.85926884, 202.11440188,
       220.39235543, 172.40288024, 176.60897931, 109.04656567,
       276.37789836,  90.99941821, 289.37221147, 119.56

In [20]:
import pandas as pd

In [21]:
df=pd.DataFrame(y_predict_data)

In [22]:
df

0
0    105.529748
1    105.803920
2    178.608572
3     79.382878
4     52.958687
..          ...
106  246.412356
107  234.963933
108  191.512983
109  168.332545
110  163.029652

[111 rows x 1 columns]

In [23]:
X_test_data=df.to_csv('X_test_data.csv',index=True)

In [24]:
X_test_data